# Generated by Django 2.2 on 2020-04-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyvalue_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyValuePairFile',
            new_name='KeyFilePair',
        ),
    ]
